"""Added required tables

Revision ID: 56fb4d03429e
Revises: 
Create Date: 2022-04-29 13:24:45.129336

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '56fb4d03429e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('edrpou_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organization_pkey'),
    sa.UniqueConstraint('edrpou_code', name='organization_edrpou_code_key'),
    sa.UniqueConstraint('name', name='organization_name_key')
    )
    # ### end Alembic commands ###
